name: asistencias_uni
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  
  # Librerías de iconos y persistencia
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.5

  # Librerías para Notificaciones
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # --- AQUÍ AGREGUÉ LA LIBRERÍA CORRECTAMENTE ---
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true

# --- AQUÍ VA LA CONFIGURACIÓN DEL ICONO ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21